from utils import strings
from models.pinecone_client import PINECONE
from utils.functions import v1_json_process_docs, v2_json_process_docs, v2_markdown_process_docs, \
    v2_custom3_process_docs, v2_1_json_process_docs, v2_1_html_process_docs, \
    v2_1_markdown_process_docs, v2_1_custom1_process_docs, v2_1_custom2_process_docs, v2_1_toml_process_docs, \
    v2_1_custom4_process_docs, v2_1_unstruct_process_docs, io_process_docs
from utils.functions import v1_html_process_docs, v2_html_process_docs, unstruct_process_docs
from utils.functions import v2_toml_process_docs, v2_custom1_process_docs, v2_custom2_process_docs

v0_extraction_vectordb = PINECONE(strings.extraction_v0_index)
v1_extraction_vectordb = PINECONE(strings.extraction_v1_index)
v2_extraction_vectordb = PINECONE(strings.extraction_v2_index)
v2_1_extraction_vectordb = PINECONE(strings.extraction_v2_1_index)
unstruct_io_vectordb = PINECONE(strings.unstructured_io_index)

stashed_format_lists = [
    {'id': 'v1-json',
     'version': 1,
     'query_str': strings.json_question,
     'llm_msg_str': strings.json_llm_message,
     'get_docs_func': v1_json_process_docs,
     'vector_db': v1_extraction_vectordb,
     'doc_count': 4},
    {'id': 'v1-html',
     'version': 1,
     'query_str': strings.html_question,
     'llm_msg_str': strings.html_llm_message,
     'get_docs_func': v1_html_process_docs,
     'vector_db': v1_extraction_vectordb,
     'doc_count': 4},
    {'id': 'v2-toml',
     'version': 2,
     'query_str': strings.toml_question,
     'llm_msg_str': strings.toml_llm_message,
     'get_docs_func': v2_toml_process_docs,
     'vector_db': v2_extraction_vectordb,
     'doc_count': 2},
    {'id': 'v2-custom3',
     'version': 2,
     'query_str': strings.toml_question,
     'llm_msg_str': strings.toml_llm_message,
     'get_docs_func': v2_custom3_process_docs,
     'vector_db': v2_extraction_vectordb,
     'doc_count': 2},
    {'id': 'v0-unstruct',
     'version': 0,
     'query_str': strings.unstructured_question,
     'llm_msg_str': strings.unstructured_llm_message,
     'get_docs_func': unstruct_process_docs,
     'vector_db': v0_extraction_vectordb,
     'doc_count': 4},
    {'id': 'v2-md',
     'version': 2,
     'query_str': strings.md_question,
     'llm_msg_str': strings.md_llm_message,
     'get_docs_func': v2_markdown_process_docs,
     'vector_db': v2_extraction_vectordb,
     'doc_count': 4},
    {'id': 'v2-jon',
     'version': 2,
     'query_str': strings.json_question,
     'llm_msg_str': strings.json_llm_message,
     'get_docs_func': v2_json_process_docs,
     'vector_db': v2_extraction_vectordb,
     'doc_count': 4},
    {'id': 'v2-html',
     'version': 2,
     'query_str': strings.html_question,
     'llm_msg_str': strings.html_llm_message,
     'get_docs_func': v2_html_process_docs,
     'vector_db': v2_extraction_vectordb,
     'doc_count': 4},
    {'id': 'v2-custom1',
     'version': 2,
     'query_str': strings.html_question,
     'llm_msg_str': strings.html_llm_message,
     'get_docs_func': v2_custom1_process_docs,
     'vector_db': v2_extraction_vectordb,
     'doc_count': 4},
    {'id': 'v2-custom2',
     'version': 2,
     'query_str': strings.json_question,
     'llm_msg_str': strings.json_llm_message,
     'get_docs_func': v2_custom2_process_docs,
     'vector_db': v2_extraction_vectordb,
     'doc_count': 4},
    {'id': 'v2.1-toml',
     'version': 2.1,
     'query_str': strings.toml_question,
     'llm_msg_str': strings.toml_llm_message,
     'get_docs_func': v2_1_toml_process_docs,
     'vector_db': v2_1_extraction_vectordb,
     'doc_count': 2},
]

v2_1_format_list = [
    {'id': 'v2.1-unstruct',
     'version': 2.1,
     'query_str': strings.unstructured_question,
     'llm_msg_str': strings.unstructured_llm_message,
     'get_docs_func': v2_1_unstruct_process_docs,
     'vector_db': v2_1_extraction_vectordb,
     'doc_count': 3},
    {'id': 'v2.1-md',
     'version': 2.1,
     'query_str': strings.md_question,
     'llm_msg_str': strings.md_llm_message,
     'get_docs_func': v2_1_markdown_process_docs,
     'vector_db': v2_1_extraction_vectordb,
     'doc_count': 3},
    {'id': 'v2.1-json',
     'version': 2.1,
     'query_str': strings.json_question,
     'llm_msg_str': strings.json_llm_message,
     'get_docs_func': v2_1_json_process_docs,
     'vector_db': v2_1_extraction_vectordb,
     'doc_count': 3},
    {'id': 'v2.1-html',
     'version': 2.1,
     'query_str': strings.html_question,
     'llm_msg_str': strings.html_llm_message,
     'get_docs_func': v2_1_html_process_docs,
     'vector_db': v2_1_extraction_vectordb,
     'doc_count': 3},
    {'id': 'v2.1-custom1',
     'version': 2.1,
     'query_str': strings.html_question,
     'llm_msg_str': strings.html_llm_message,
     'get_docs_func': v2_1_custom1_process_docs,
     'vector_db': v2_1_extraction_vectordb,
     'doc_count': 3},
    {'id': 'v2.1-custom2',
     'version': 2.1,
     'query_str': strings.json_question,
     'llm_msg_str': strings.json_llm_message,
     'get_docs_func': v2_1_custom2_process_docs,
     'vector_db': v2_1_extraction_vectordb,
     'doc_count': 3},
    {'id': 'v2.1-custom4',
     'version': 2.1,
     'query_str': strings.code_question,
     'llm_msg_str': strings.code_llm_message,
     'get_docs_func': v2_1_custom4_process_docs,
     'vector_db': v2_1_extraction_vectordb,
     'doc_count': 3},
]

format_lists = [
    {'id': 'unstructured-io',
     'version': -1,
     'query_str': strings.unstructured_question,
     'llm_msg_str': strings.unstructured_llm_message,
     'get_docs_func': io_process_docs,
     'vector_db': unstruct_io_vectordb,
     'doc_count': 25}
]
